# Generated by Django 3.0.3 on 2020-02-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome do cliente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='PlanogramProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Preço do produto')),
                ('pair', models.IntegerField(verbose_name='Número de par')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='PlanogramProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(verbose_name='Desconto em (%)')),
                ('begin', models.DateTimeField(verbose_name='Data e hora inicial')),
                ('end', models.DateTimeField(verbose_name='Data e hora final')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do produto')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Imagem em base64')),
                ('barcode', models.CharField(max_length=32, verbose_name='Código de barras')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Produto ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token da venda')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Customer', verbose_name='Nome do cliente')),
                ('products', models.ManyToManyField(to='inventory.PlanogramProduct', verbose_name='Produtos vendidos')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='planogramproduct',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.PlanogramProductDiscount', verbose_name='Desconto no item do planograma'),
        ),
        migrations.AddField(
            model_name='planogramproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product', verbose_name='Produto da Nota Fiscal'),
        ),
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=8, verbose_name='Versão do Planograma')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('products', models.ManyToManyField(to='inventory.PlanogramProduct', verbose_name='Produtos do Planograma')),
            ],
            options={
                'verbose_name': 'Planograma',
                'verbose_name_plural': 'Planogramas',
            },
        ),
        migrations.CreateModel(
            name='PicklistProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product')),
            ],
            options={
                'verbose_name': 'Produto de Picklist',
                'verbose_name_plural': 'Produtos de Picklist',
            },
        ),
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=32, null=True, verbose_name='Versão da Picklist')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('products', models.ManyToManyField(to='inventory.PicklistProduct')),
            ],
            options={
                'verbose_name': 'Picklist',
                'verbose_name_plural': 'Picklists',
            },
        ),
    ]
