# Generated by Django 3.0.3 on 2020-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Captura iniada em:')),
                ('onbarcode', models.BooleanField(blank=True, null=True, verbose_name='Código de barras')),
                ('hasBluetooth', models.BooleanField(blank=True, null=True, verbose_name='Bluetooth')),
                ('hasEthernet', models.BooleanField(blank=True, null=True, verbose_name='Ethernet')),
                ('hasGPRS', models.BooleanField(blank=True, null=True, verbose_name='GPRS')),
                ('hasHDMI', models.BooleanField(blank=True, null=True, verbose_name='HDMI')),
                ('hasTouch', models.BooleanField(blank=True, null=True, verbose_name='Touch')),
                ('hasWifi', models.BooleanField(blank=True, null=True, verbose_name='Wifi')),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
        ),
    ]
